# Generated by Django 4.2.10 on 2024-02-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='JWT Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='JWT Token'),
        ),
    ]
