# Generated by Django 4.2.10 on 2024-03-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_active_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Email', 'verbose_name_plural': 'historical Users'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Users'},
        ),
    ]
